# Generated by Django 4.1.3 on 2023-01-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Contact',
        ),
    ]
