# Generated by Django 4.1.3 on 2022-12-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_mail_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mail',
            field=models.EmailField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
