# Generated by Django 4.1.3 on 2022-12-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='pa1ssword',
        ),
    ]
