# Generated by Django 4.1.3 on 2022-12-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_password_customer_pa1ssword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pa1ssword',
            new_name='password',
        ),
    ]
