# Generated by Django 4.1.3 on 2022-12-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_pa1ssword_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='name',
        ),
    ]
