# Generated by Django 4.1.3 on 2022-12-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_username_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
