# Generated by Django 4.1.3 on 2022-12-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile', models.IntegerField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
