# Generated by Django 4.1.3 on 2022-12-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customer2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer2',
        ),
    ]
