# Generated by Django 4.1.5 on 2023-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_delete_customer2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalvisitor', models.CharField(max_length=255)),
                ('tatalregister', models.CharField(max_length=225)),
                ('totalpackage', models.CharField(max_length=225)),
            ],
        ),
    ]
