# Generated by Django 4.1.3 on 2023-01-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Package',
        ),
    ]
