# Generated by Django 4.1.5 on 2023-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_rename_customer_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='DateOfEnd',
        ),
        migrations.AddField(
            model_name='package',
            name='Listfoprice',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='Prise',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
