# Generated by Django 4.1.5 on 2023-01-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_package_dateofend_package_listfoprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Listfoprice',
            new_name='Listofplace',
        ),
    ]
