# Generated by Django 4.1.5 on 2023-02-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_rename_listfoprice_package_listofplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Totalseet',
            field=models.CharField(default=26, max_length=225),
            preserve_default=False,
        ),
    ]
