# Generated by Django 4.1.5 on 2023-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_book_paymentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(max_length=225)),
                ('Code', models.CharField(max_length=225)),
                ('Bankname', models.CharField(max_length=225)),
                ('Paymentmode', models.CharField(max_length=225)),
                ('Amount', models.CharField(max_length=225)),
                ('Status', models.CharField(max_length=225)),
                ('Date', models.CharField(max_length=225)),
            ],
        ),
    ]
